<?php

namespace SNS\PlateformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
	public function getDocuments($page, $nbPerPage)
	  {
	    $query = $this->createQueryBuilder('d')
		->leftJoin('d.auteur', 'a')
		->addSelect('a')
		->orderBy('d.date', 'DESC')
		->getQuery()
	    ;

	    $query
		// On définit l'annonce à partir de laquelle commencer la liste
		->setFirstResult(($page-1) * $nbPerPage)
		// Ainsi que le nombre d'annonce à afficher sur une page
		->setMaxResults($nbPerPage)
	    ;

	    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
	    // (n'oubliez pas le use correspondant en début de fichier)
	    return new Paginator($query, true);
	  }
	
	
}
