services:
#    sns_membre.example:
#        class: SNS\MembreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    projet_user.registration.form.type:
        class: SNS\MembreBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sns_membre_registration}

    projet_user.profile.form.type:
        class: SNS\MembreBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sns_membre_profile}