<?php

namespace SNS\MembreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{
	/*public function leBureau()
	{
	  $qb = $this->createQueryBuilder('m');

	  $qb
	    ->where('m.poste = "Président" ')
	    //->andWhere('m.poste = "Vice-Président" ')
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}*/

}

